### ISSUE TITLE
Problems with SPR calculation

### ISSUE THREAD

**Issue by mingsun** [flr/FLBRP#11]
I noticed the default SPR reference points calculated with brp() include SPR.30. I am wondering is it possible for me to adjust the SPR values to be estimated, see I need SSB-SPR.40 at this moment?

**Comment by iagomosqueira** [comment]
It is able to do, although the interface is a bit convoluted. You need to modify the dimnames of the refpts slot and then refit.

```
# Create an example FLBRP

data(ple4)
psr <- fmle(as.FLSR(ple4, model='ricker'))
prp<-brp(FLBRP(ple4, psr))

# Check spr.30 values
refpts(prp)['spr.30',]

# 
dimnames(refpts(prp))$refpt[6] <- 'spr.40'
prp <- brp(prp)
refpts(prp)['spr.40',]
```

We will aim at having a better interface in the next release.

**Comment by mingsun** [comment]
Thanks for your reply.

I actually have another question. I am currently testing some length-based
Harvest Control Rules by extending a FLStock on an annual basis. Is it
possible to change the selectivity of harvest fleet, so it could simulate
effects of different length control measure?

**Comment by iagomosqueira** [comment]
If you are using `FLash::fwd()` for the projections, the combined selectivity at age is taken from the pattern in the `harvest` slot. You can look at how it is converted into selectivity by calling

```
catch.sel(stk)
```

where `stk` is your FLStock object.

When the object is extended for a number of years for projection, usually either using `stf` or `fwdWindow`, the fishing mortality at age, and thus the selectivity pattern encoded in it, for future years is set by default as some average of the last few years, depending on which method is used.

You can alter the harvest slot in the projection years in any way to specify a new selectivity pattern. For example:

```
library(FLash)

data(ple4)

# catch.sel in 2008
catch.sel(ple4)[, ac(2005:2008)]

# new object
nple4 <- ple4

# change catch.sel for 2008 projection
harvest(nple4)[, ac(2005:2008)] <- c(0.8, rep(1, 6), rep(0.4, 3))

catch.sel(nple4)[, ac(2005:2008)]

# project in 2008 for observed catch with diff selectivity
nple4 <- fwd(nple4, sr=list(model=~a,
  # To get the sasme recruitment, set mean=1 and pass values as residuals
  params=FLPar(a=1)), sr.residuals=rec(ple4)[, ac(2005:2008)], sr.residuals.mult=TRUE,
  fwdControl(data.frame(val=c(fbar(ple4[, ac(2005:2008)])), quantity='f',
    year=2005:2008)))

# Compare abundances at age
stock.n(ple4)[, ac(2005:2008)]
stock.n(nple4)[,  ac(2005:2008)]

# Compare F at age
harvest(nple4)[, ac(2005:2008)]
harvest(ple4)[, ac(2005:2008)]

# But fbar is the same, as this was the target set to fwd()
fbar(ple4)[, ac(2005:2008)]
fbar(nple4)[, ac(2005:2008)]
```

**Comment by mingsun** [comment]
Hi ,

I have got another question following the changed selectivity.

See, I have stock of 9 age groups, and I reassign the selectivity-at-age
for the projection as c(0.5,0.5,0.5,1,0,0,0,0,1), which is a typical slot
control method. But when I run FLXSA to assess the finished projection, I
found that the XSA automatically arrange the selectivity differently from
what I assigned, especially with the full selectivity at age-9 (it became
extremely low).

So my question is how can force the selectivity arrangement when conducting
XSA assessments to make it follow my expected pattern of selectivity?


May thanks,
Ming

**Comment by iagomosqueira** [comment]
XSA does not estimate selectivity, but it is inferred from the resulting pattern in F-at-age, which is informed by the catch-at-age and the indices-at-age. So you cannot force FLXSA to work with the selectivity of your choice, that is only an option in projections with Flash::fwd.

If you want an stock assessment to estimate abundances under your selectivity assumption you will have to choose an statistical catch-at-age model where the shape can be made to approximate your vector. For example, using FLa4a you could use a logistic function. See the example in

http://www.flr-project.org/doc/Statistical_catch_at_age_models_in_FLa4a.html

and search for "logistic form".
