### ISSUE TITLE
Package FLBRP not installing 

### ISSUE THREAD

**Issue by Ikpewe** [flr/FLBRP#12]
I am trying to install the package FLBRP and the error text below is what I am having. Please could any one be of help?
error :
Packages which are only available in source form, and may need compilation of C/C++/Fortran:
  ‘FLash’ ‘FLBRP’

**Comment by iagomosqueira** [comment]
Are you in Windows? R 3.5? Binary packages are available for R 3.4, and for those two you need to be running R 32 bits. For 64 bits, again in R 3.4, you need to install FLRP and FLasher. Some code will differ though, you can check the FLasher tutorial.   

  

  
  
  
  
  
>

**Comment by Ikpewe** [comment]
Hi,

Yea I am using windows and R 3.5. I will trying again.

Thanks.

**Comment by iagomosqueira** [comment]
Binary pkgs for R 3.5 will be distributed in a few weeks
  
  

  
  
  
  
  
>
