### ISSUE TITLE
installing on a Mac

### ISSUE THREAD

**Issue by mebrooks** [flr/FLBRP#13]
I'm running R 3.5.2 with macOS 10.14.2. I was able to install most of the FL suite, but ran into problems with FLBRP.

```
> install.packages("FLBRP", repos="http:///flr-project.org/R")
Installing package into ‘/Users/molliebrooks/Library/R/3.5/library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http:///flr-project.org/R/bin/macosx/el-capitan/contrib/3.5:
  cannot open URL 'http:///flr-project.org/R/bin/macosx/el-capitan/contrib/3.5/PACKAGES'
Package which is only available in source form, and may need compilation of C/C++/Fortran:
  ‘FLBRP’
Do you want to attempt to install these from sources? (Yes/no/cancel) y
installing the source package ‘FLBRP’

trying URL 'http:///flr-project.org/R/src/contrib/FLBRP_2.5.3.tar.gz'
Content type 'application/gzip' length 233849 bytes (228 KB)
==================================================
downloaded 228 KB

* installing *source* package ‘FLBRP’ ...
** libs
/usr/local/clang4/bin/clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -I../inst/include -fPIC  -Wall -g -O2  -c init.c -o init.o
/usr/local/clang4/bin/clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -I../inst/include -std=gnu++11 -fPIC  -Wall -g -O2  -c FLCoreClasses.cpp -o FLCoreClasses.o
FLCoreClasses.cpp:26:10: warning: unused variable 'dimnames' [-Wunused-variable]
         dimnames = GET_DIMNAMES(v);
         ^
FLCoreClasses.cpp:748:14: warning: unused variable 'z' [-Wunused-variable]
      double z = m(iage, iyr, iunit, iseason, iarea, iter) + harvest(iage, iyr, iunit, iseason, iarea, iter);
             ^
2 warnings generated.
/usr/local/clang4/bin/clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include  -I../inst/include -std=gnu++11 -fPIC  -Wall -g -O2  -c FLBRP.cpp -o FLBRP.o
In file included from FLBRP.cpp:11:
In file included from ../inst/include/FLBRP.h:20:
In file included from ../inst/include/adolc/adtl.h:20:
In file included from /usr/local/clang4/bin/../include/c++/v1/ostream:138:
In file included from /usr/local/clang4/bin/../include/c++/v1/ios:216:
/usr/local/clang4/bin/../include/c++/v1/__locale:870:34: error: too many arguments provided to function-like macro invocation
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
                                 ^
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:1427:9: note: macro 'length' defined here
#define length(x)               Rf_length(x)
        ^
In file included from FLBRP.cpp:11:
In file included from ../inst/include/FLBRP.h:20:
In file included from ../inst/include/adolc/adtl.h:20:
In file included from /usr/local/clang4/bin/../include/c++/v1/ostream:138:
In file included from /usr/local/clang4/bin/../include/c++/v1/ios:216:
/usr/local/clang4/bin/../include/c++/v1/__locale:870:15: error: expected ';' at end of declaration list
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
              ^
/usr/local/clang4/bin/../include/c++/v1/__locale:955:34: error: too many arguments provided to function-like macro invocation
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
                                 ^
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:1427:9: note: macro 'length' defined here
#define length(x)               Rf_length(x)
        ^
In file included from FLBRP.cpp:11:
In file included from ../inst/include/FLBRP.h:20:
In file included from ../inst/include/adolc/adtl.h:20:
In file included from /usr/local/clang4/bin/../include/c++/v1/ostream:138:
In file included from /usr/local/clang4/bin/../include/c++/v1/ios:216:
/usr/local/clang4/bin/../include/c++/v1/__locale:955:15: error: expected ';' at end of declaration list
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
              ^
/usr/local/clang4/bin/../include/c++/v1/__locale:1039:34: error: too many arguments provided to function-like macro invocation
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
                                 ^
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:1427:9: note: macro 'length' defined here
#define length(x)               Rf_length(x)
        ^
In file included from FLBRP.cpp:11:
In file included from ../inst/include/FLBRP.h:20:
In file included from ../inst/include/adolc/adtl.h:20:
In file included from /usr/local/clang4/bin/../include/c++/v1/ostream:138:
In file included from /usr/local/clang4/bin/../include/c++/v1/ios:216:
/usr/local/clang4/bin/../include/c++/v1/__locale:1039:15: error: expected ';' at end of declaration list
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
              ^
/usr/local/clang4/bin/../include/c++/v1/__locale:1125:34: error: too many arguments provided to function-like macro invocation
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
                                 ^
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:1427:9: note: macro 'length' defined here
#define length(x)               Rf_length(x)
        ^
In file included from FLBRP.cpp:11:
In file included from ../inst/include/FLBRP.h:20:
In file included from ../inst/include/adolc/adtl.h:20:
In file included from /usr/local/clang4/bin/../include/c++/v1/ostream:138:
In file included from /usr/local/clang4/bin/../include/c++/v1/ios:216:
/usr/local/clang4/bin/../include/c++/v1/__locale:1125:15: error: expected ';' at end of declaration list
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
              ^
FLBRP.cpp:407:22: warning: unused variable 'recruits' [-Wunused-variable]
              double recruits = Recruits(FMult, iIter);
                     ^
FLBRP.cpp:711:14: warning: unused variable 't2' [-Wunused-variable]
   double t, t2, slopeOrig;
             ^
FLBRP.cpp:1896:11: warning: unused variable 't' [-Wunused-variable]
   double t      = ReturnValue.getValue();
          ^
FLBRP.cpp:1909:8: warning: unused variable 'iAge' [-Wunused-variable]
   int iAge, iUnit, iSeason, iArea;
       ^
FLBRP.cpp:1916:11: warning: unused variable 't' [-Wunused-variable]
   double t      = ReturnValue.getValue();
          ^
5 warnings and 8 errors generated.
make: *** [FLBRP.o] Error 1
ERROR: compilation failed for package ‘FLBRP’
* removing ‘/Users/molliebrooks/Library/R/3.5/library/FLBRP’

The downloaded source packages are in
	‘/private/var/folders/8t/zsp25_b17td7j1y5d_nmfqt00000gq/T/RtmppDf7wn/downloaded_packages’
Warning message:
In install.packages("FLBRP", repos = "http:///flr-project.org/R") :
  installation of package ‘FLBRP’ had non-zero exit status
```

**Comment by iambaim** [comment]
Hi, 
you might want to try this pull request: #14  .

**Comment by iagomosqueira** [comment]
Now in master, please test and report., Thanks, @iambaim

**Comment by mebrooks** [comment]
I'll try this out next week. Thanks for working on it!

**Comment by mebrooks** [comment]
Yep. I was able to install and run most of an [example](http://www.flr-project.org/doc/Reference_points_for_fisheries_management_with_FLBRP.html). I think the new error I got (below) was unrelated, so I'll close this.
```
> p$data <- within(p$data,{minrge <- NA
+                          minrge <- replace(minrge,grep("v. F",pnl),rge4@.Data["min","harvest",])
+                          minrge <- replace(minrge,grep("v. SSB",pnl),rge4@.Data["max","ssb",])
+                          maxrge <- NA
+                          maxrge <- replace(maxrge,grep("v. F",pnl),rge4@.Data["max","harvest",])
+                          maxrge <- replace(maxrge,grep("v. SSB",pnl),rge4@.Data["min","ssb",])})
Error in grep("v. F", pnl) : object 'pnl' not found
```

**Comment by iagomosqueira** [comment]
Great. Let us know if you try with any of the other pkgs using C++

**Comment by jimianelli** [comment]
install.packages("FLBRP", repos="http:///flr-project.org/R")
Installing package into ‘/Users/jim/Library/R/3.6/library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http:///flr-project.org/R/bin/macosx/el-capitan/contrib/3.6:
  cannot open URL 'http:///flr-project.org/R/bin/macosx/el-capitan/contrib/3.6/PACKAGES'
Package which is only available in source form, and may need
  compilation of C/C++/Fortran: ‘FLBRP’
Do you want to attempt to install these from sources? (Yes/no/cancel) y
installing the source package ‘FLBRP’

trying URL 'http:///flr-project.org/R/src/contrib/FLBRP_2.5.3.tar.gz'
Content type 'application/gzip' length 233849 bytes (228 KB)
==================================================
downloaded 228 KB

* installing *source* package ‘FLBRP’ ...
** using staged installation
** libs
/usr/local/clang8/bin/clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -I../inst/include -fPIC  -Wall -g -O2  -c init.c -o init.o
/usr/local/clang8/bin/clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -I../inst/include -std=gnu++11 -fPIC  -Wall -g -O2  -c FLCoreClasses.cpp -o FLCoreClasses.o
FLCoreClasses.cpp:26:10: warning: unused variable 'dimnames' [-Wunused-variable]
         dimnames = GET_DIMNAMES(v);
         ^
FLCoreClasses.cpp:748:14: warning: unused variable 'z' [-Wunused-variable]
      double z = m(iage, iyr, iunit, iseason, iarea, iter) + harvest(iage, iyr, iunit, iseason, iarea, iter);
             ^
2 warnings generated.
/usr/local/clang8/bin/clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -I../inst/include -std=gnu++11 -fPIC  -Wall -g -O2  -c FLBRP.cpp -o FLBRP.o
In file included from FLBRP.cpp:11:
In file included from ../inst/include/FLBRP.h:20:
In file included from ../inst/include/adolc/adtl.h:20:
In file included from /usr/local/clang8/bin/../include/c++/v1/ostream:138:
In file included from /usr/local/clang8/bin/../include/c++/v1/ios:216:
/usr/local/clang8/bin/../include/c++/v1/__locale:917:34: error: too many arguments provided to function-like macro invocation
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
                                 ^
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:1481:9: note: macro 'length' defined here
#define length(x)               Rf_length(x)
        ^
In file included from FLBRP.cpp:11:
In file included from ../inst/include/FLBRP.h:20:
In file included from ../inst/include/adolc/adtl.h:20:
In file included from /usr/local/clang8/bin/../include/c++/v1/ostream:138:
In file included from /usr/local/clang8/bin/../include/c++/v1/ios:216:
/usr/local/clang8/bin/../include/c++/v1/__locale:917:15: error: expected ';' at end of declaration list
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
              ^
/usr/local/clang8/bin/../include/c++/v1/__locale:1002:34: error: too many arguments provided to function-like macro invocation
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
                                 ^
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:1481:9: note: macro 'length' defined here
#define length(x)               Rf_length(x)
        ^
In file included from FLBRP.cpp:11:
In file included from ../inst/include/FLBRP.h:20:
In file included from ../inst/include/adolc/adtl.h:20:
In file included from /usr/local/clang8/bin/../include/c++/v1/ostream:138:
In file included from /usr/local/clang8/bin/../include/c++/v1/ios:216:
/usr/local/clang8/bin/../include/c++/v1/__locale:1002:15: error: expected ';' at end of declaration list
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
              ^
/usr/local/clang8/bin/../include/c++/v1/__locale:1086:34: error: too many arguments provided to function-like macro invocation
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
                                 ^
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:1481:9: note: macro 'length' defined here
#define length(x)               Rf_length(x)
        ^
In file included from FLBRP.cpp:11:
In file included from ../inst/include/FLBRP.h:20:
In file included from ../inst/include/adolc/adtl.h:20:
In file included from /usr/local/clang8/bin/../include/c++/v1/ostream:138:
In file included from /usr/local/clang8/bin/../include/c++/v1/ios:216:
/usr/local/clang8/bin/../include/c++/v1/__locale:1086:15: error: expected ';' at end of declaration list
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
              ^
/usr/local/clang8/bin/../include/c++/v1/__locale:1172:34: error: too many arguments provided to function-like macro invocation
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
                                 ^
/Library/Frameworks/R.framework/Resources/include/Rinternals.h:1481:9: note: macro 'length' defined here
#define length(x)               Rf_length(x)
        ^
In file included from FLBRP.cpp:11:
In file included from ../inst/include/FLBRP.h:20:
In file included from ../inst/include/adolc/adtl.h:20:
In file included from /usr/local/clang8/bin/../include/c++/v1/ostream:138:
In file included from /usr/local/clang8/bin/../include/c++/v1/ios:216:
/usr/local/clang8/bin/../include/c++/v1/__locale:1172:15: error: expected ';' at end of declaration list
    int length(state_type& __st, const extern_type* __frm, const extern_type* __end, size_t __mx) const
              ^
FLBRP.cpp:407:22: warning: unused variable 'recruits' [-Wunused-variable]
              double recruits = Recruits(FMult, iIter);
                     ^
FLBRP.cpp:711:14: warning: unused variable 't2' [-Wunused-variable]
   double t, t2, slopeOrig;
             ^
FLBRP.cpp:1896:11: warning: unused variable 't' [-Wunused-variable]
   double t      = ReturnValue.getValue();
          ^
FLBRP.cpp:1909:8: warning: unused variable 'iAge' [-Wunused-variable]
   int iAge, iUnit, iSeason, iArea;
       ^
FLBRP.cpp:1916:11: warning: unused variable 't' [-Wunused-variable]
   double t      = ReturnValue.getValue();
          ^
5 warnings and 8 errors generated.
make: *** [FLBRP.o] Error 1
ERROR: compilation failed for package ‘FLBRP’
* removing ‘/Users/jim/Library/R/3.6/library/FLBRP’

The downloaded source packages are in
	‘/private/var/folders/qb/mr3sb1m1403cqwg1yy0qtjz80000gn/T/RtmptJlhW4/downloaded_packages’
Warning message:
In install.packages("FLBRP", repos = "http:///flr-project.org/R") :
  installation of package ‘FLBRP’ had non-zero exit status
